### ISSUE TITLE
Polygon enlargement

### ISSUE THREAD

**Issue by rosivda** [heitzmann/gdspy#1]
@heitzmann : Our chip design workflow is based on gdspy 0.7 and is built on gdspy geometry objects and gdspy boolean operations. There is one feature, however, that requires us to use additional packages to complete the design cycle. In our mask layouts, it is critical to have the ability to introduce CD bias to account for the linewidth reduction during the fabrication process. In mathematical terms, one needs to have the ability to enlarge polygons by a predefined amount in the direction that is normal to the polygon surface... thus a request for this feature. Thank you.

**Comment by heitzmann** [comment]
@rosivda, please take a look at the [offset function](http://gdspy.readthedocs.org/en/latest/construction.html#offset).
I believe it does exactly what you are looking for.
