### ISSUE TITLE
Filleting with voids error

### ISSUE THREAD

**Issue by trezitorul** [heitzmann/gdspy#102]
When filleting a polygon with an enclosed void. The fillet function fillets the intersection between the line connecting the void to the outside of the polygon. 
![image](https://user-images.githubusercontent.com/1572547/66360658-ed062c80-e949-11e9-8fc9-12a5a03e3160.png)

**Comment by heitzmann** [comment]
@trezitorul This is a known limitation... Is it possible for you to fillet before creating the holes? Otherwise, the solution would be to create small rectangles to patch the undesired fillets (using a boolean union).

**Comment by trezitorul** [comment]
Ah I see, so when making complex structures like this it is best to keep everything as independent shapes and at the end integrate and fillet.

**Comment by heitzmann** [comment]
Yes, it strongly depends on the layout. Detecting and deciding whether such edges/vertices should be included in the fillet operation is a hard problem and I can see situations where the user would indeed want the operation to be performed.

In cases like yours, a quite general solution is to fillet before the boolean subtraction.
