### ISSUE TITLE
Meaning and purpose of 'datatype' argument

### ISSUE THREAD

**Issue by Miakatt** [heitzmann/gdspy#104]
Can you please explain what the 'datatype' argument does in the final GDS file?  I have an issue with a Raith Voyager machine which I posted about here: https://github.com/heitzmann/gdspy/issues/23#issuecomment-540397802

The engineers at Raith are looking into this and mentioned that they've had problems with some kind of sublayers due to this 'datatype' argument that the NanoSuite software (that runs the Raith machine) is not able to handle. 
Is this argument required to produce a final .gds file/

**Comment by heitzmann** [comment]
Hi @Miakatt, in the GDSII format, all polygons must be tagged with 2 positive integer flags: layer and datatype — they are not optional. They also have no meaning or purpose explicitly defined in the format; it's up to the user to attach a meaning to them. For example, I've used e-beam tools where the layer would be mapped to electron dose and datatype had no meaning (it was simply ignored). There are mask companies that use both layer and datatype to indicate to which step in the processing line the polygons refer. It is really up to Raith to define how they interpret the datatype field (it seems from your description that they are using it together with layers). I have used Raith software before (not NanoSuite) and, if I recall correctly, datatype was mapped to electron dose in my case.
