### ISSUE TITLE
Scaling, mirroring and rotating cells

### ISSUE THREAD

**Issue by tomasstankevic** [heitzmann/gdspy#105]
Hi, I cannot find the way how to scale, mirror or rotate cell references. I can only see the translation option. Are there any plans to implement these operations in the future?

**Comment by heitzmann** [comment]
@tomasstankevic There are arguments for all of those options in the constructor:
https://gdspy.readthedocs.io/en/stable/gettingstarted.html#references
https://gdspy.readthedocs.io/en/stable/reference.html#cellreference
