### ISSUE TITLE
Cannot Compile Clipper on MacOS

### ISSUE THREAD

**Issue by Lambdauv** [heitzmann/gdspy#109]
Hi Everyone,

My MacOS is Catalina 10.15 and I am trying to install gdspy on it. However, neither pip install gdspy nor python setup.py install works and they all got stuck with the following error.

> building 'gdspy.clipper' extension
> gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Roseldon/anaconda3/include -arch x86_64 -I/Users/Roseldon/anaconda3/include -arch x86_64 :/usr/local/include -I/Users/Roseldon/anaconda3/include/python3.7m -c gdspy/clipper.cpp -o build/temp.macosx-10.7-x86_64-3.7/gdspy/clipper.o -std=c++11 -mmacosx-version-min=10.9
> gcc: error: :/usr/local/include: No such file or directory
> error: command 'gcc' failed with exit status 1

I have been really straggling to figure out a solution for this. The folder /usr/local/include does exist and I don't know why it doesn't see it.

Best

**Comment by heitzmann** [comment]
@Lambdauv, I dont have access to OS X, but the colon (`:`) before the path looks odd to me... do you have both XCode and Command Line Tools properly updated?
