### ISSUE TITLE
ValueError: Operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by dwaardenburg** [heitzmann/gdspy#111]
Dear heitzmann,

I have made a piece of code that gives me quite a weird error.
The code itself is kinda hard to show due to IP rights.
Would you have any clue where this error could come from?

This is the error:
File "/anaconda3/lib/python3.7/site-packages/gdspy/__init__.py", line 6648, in write_cell
    self._outfile.write(cell.to_gds(self._res, timestamp))
  File "/anaconda3/lib/python3.7/site-packages/gdspy/__init__.py", line 4878, in to_gds
    data.extend(path.to_gds(multiplier) for path in self.paths)
  File "/anaconda3/lib/python3.7/site-packages/gdspy/__init__.py", line 4878, in <genexpr>
    data.extend(path.to_gds(multiplier) for path in self.paths)
  File "/anaconda3/lib/python3.7/site-packages/gdspy/__init__.py", line 3103, in to_gds
    return self.to_polygonset().to_gds(multiplier)
  File "/anaconda3/lib/python3.7/site-packages/gdspy/__init__.py", line 3070, in to_polygonset
    polygons = self.get_polygons(True)
  File "/anaconda3/lib/python3.7/site-packages/gdspy/__init__.py", line 2866, in get_polygons
    pa = pts[:-1] + vn * (sign * 0.5 * self.widths[:-1, kk:kk + 1])
ValueError: operands could not be broadcast together with shapes (4,2) (5,1)

**Comment by dwaardenburg** [comment]
The path[i] variables are points. The code runs fine if I only use the first and last line of this segment.

**Comment by heitzmann** [comment]
@dwaardenburg I can look into it to try to figure out what's wrong, but I'm quite busy this week, so it could be a few days. In the mean time, do you have by any chance a complete example so that I can reproduce the bug myself?

**Comment by dwaardenburg** [comment]
So far it seems that the flexpath.segment method might just continue if the point is a list of points. I thought that was an option. Let me check tomorrow if that was the case.

**Comment by heitzmann** [comment]
[`FlexPath.segment`](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.FlexPath.segment) accepts only a single (x, y) point, not a list... is that the issue? From your code it seemed you were already passing single points, but you'd have to make sure path[i] and path_widths[i] are what you expect.

Let me know if you find out anything else...

**Comment by heitzmann** [comment]
@dwaardenburg, I believe I found the problem (completely by chance while working on something else): the line `path_list.append(gd.FlexPath(to_point, to_end_width))` initializes `FlexPath` with `to_point`, which I assume is a size-2 vector. However, the first argument of `FlexPath` must be an [N×2 array](https://gdspy.readthedocs.io/en/stable/reference.html#flexpath).

I believe if you replace that line with `path_list.append(gd.FlexPath([to_point], to_end_width))` the issue will be solved. Could you give it a try?

This is a common enough use case that I should probably include as a special case for the first argument.

**Comment by heitzmann** [comment]
It's been a while, but I believe this commit solves the issue.
