### ISSUE TITLE
How to clear the library after a run?

### ISSUE THREAD

**Issue by Harbing** [heitzmann/gdspy#112]
When I try to rerun the program, it always say gdspy library already exist and I have to restart python. Any method I can clear the cache and rerun without restarting the console?

**Comment by heitzmann** [comment]
If I understand your question, you can simply do
```python
gdspy.current_library = gdspy.GdsLibrary()
```
to [reset](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.current_library).

**Comment by Harbing** [comment]
Thanks. This is exactly what I need.
