### ISSUE TITLE
`read_gds` cannot load a rectangle.

### ISSUE THREAD

**Issue by mshrn** [heitzmann/gdspy#116]
I get a warning while reading gds file;
`lib = GdsLibrary(infile="original.GDS")` raises two warnings: `UserWarning [GDSPY] Record type BOX (2D) is not supported` and `[GDSPY] Record type BOXTYPE (2E) is not supported.`
I exported the library: `lib.write_gds("duplicated.GDS")`, and found out that simple rectangle and chamfered rectangle are not loaded. (If you need, I will upload gds files in somewhere. I do not know where to upload in such a case.)
I read Issues #90 and #66, and I do not know why such simple figures are not supported.
Could you tell me why?

**Comment by heitzmann** [comment]
I believe commit a06a1c7079a1958e5d7abe9625a60c6e0ce44cf0 solves this issue. I've never encountered a file with BOX elements, so I'd never felt the need for implementing support for them before.

**Comment by mshrn** [comment]
I greatly appreciate your quick bug-fix. 
I utilize a gds file in order to organize patterns of converging electronic and photonic integrated circuits. Semiconductor electronic devices never requires box-shaped objects?

I modify library.py as you tell me and tested, but, however, an error is raised:
```
line 2456, in _create_path
    return FlexPath(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'width'
```
It seems that we need to calculate a `width` from a box object data. I tried to decode the binary file  based on `_record_reader`, but I failed because of my poor understanding of gds format.
I have uploaded a test gds file at [here](https://drive.google.com/open?id=1Hd7fJENxVJND8AdGtFYeIIndklIzPViH).
Could you fix the problem?

Best regards.

**Comment by mshrn** [comment]
Successfully load a rectangle shape! Thank you so much!
