### ISSUE TITLE
Merging polygons in a cell

### ISSUE THREAD

**Issue by jethiercrc** [heitzmann/gdspy#119]
I have a number of polygons ( created by gdspy.Polygon() ) that have been added to a cell (using poly_cell.add). I'd like to merge all of the polygons in the cell together to have a minimum number of polygons present (to reduce filesize and complexity at the fabrication end). Is this possible within a cell?

**Comment by heitzmann** [comment]
@jethiercrc You should probably perform the union (merging) before adding to the cell, otherwise the originals and the result will both be present. Take a look at the docs for [`gdspy.boolean`](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.boolean).

```python
polygon_list = [...]  # list with all polygons
result = gdspy.boolen(polygon_list, None, "or")
cell.add(result)
```
