### ISSUE TITLE
Descriptor improvements / installation instructions

### ISSUE THREAD

**Issue by rosivda** [heitzmann/gdspy#12]
I would like to propose some improvements to the description of Gdspy and clarifications to the installation instructions.

# GDSPY README

Gdspy is a Python module for creating/importing/merging of GDSII stream files. It includes key libraries for creating complex CAD layouts:
* Boolean operations on polygons (AND, OR, NOT, XOR) based on clipping algorithm
* Polygon offset (inward and outward rescaling of polygons)
* Efficient point-in-polygon solutions for large array sets

Gdspy also includes a simple layout viewer. Typical applications of Gdspy are in the fields of electronic chip design, planar lightwave circuit design, and mechanical engineering.

### Dependencies:
* [Python](https://www.python.org/) (tested with versions 2.7 and 3.5)
* [Numpy](http://www.numpy.org/) (tested with 1.11.1)
* C compiler (needed only if built from source)

### LINUX / OS X
Option 1: Download Gdspy and build from source using the following command:
```
python setup.py install
```
Option 2: Install Gdspy with pip:
```
pip install gdspy
```
### WINDOWS
Option 1: The preferred option is to install Gdspy using pre-compiled binaries that can be downloaded [here](https://github.com/heitzmann/gdspy/releases) for 32-bit or 64-bit systems. First, download a portable [WinPython](https://winpython.github.io/) (tested with WinPython-64bit-3.5.2.2), run the executable to unpack the files to a directory. In the directory, run "WinPython Control Panel.exe" and click "Add packages". Select the downloaded Gdspy binary executable and click on "Install packages".

Option 2: Gdspy can also be built from source using a development environment to compile the boolean extension module using ``` python setup.py install ``` command.

**Comment by heitzmann** [comment]
Looks great! Merged with original README.
