### ISSUE TITLE
extract() function broken due to GdsLibrary API change

### ISSUE THREAD

**Issue by collineps** [heitzmann/gdspy#120]
Calling `gdspy.GdsLibrary.extract()` results in the following error:

```
File "/usr/local/lib/python3.7/site-packages/gdspy/library.py", line 2598, in extract
  cell = self.cell_dict.get(cell, cell)
AttributeError: 'GdsLibrary' object has no attribute 'cell_dict'
```
According to the [docs](https://gdspy.readthedocs.io/en/stable/reference.html#gdslibrary), `self.cell_dict` is now `self.cells`.

This error is easily fixed by changing [line 2598](https://github.com/heitzmann/gdspy/blob/2f98a9ab51f7c73665a264fde71447262aa3a4db/gdspy/library.py#L2598) in `library.py`:
    `cell = self.cell_dict.get(cell, cell)`
to:
    `cell = self.cells.get(cell, cell)`

While `gdspy.GdsLibrary.extract()` will be deprecated as discussed in Issue #113, having it broken is probably not desired.

**Comment by heitzmann** [comment]
Thanks! Fixed!
