### ISSUE TITLE
Documentation for version 1.4.2

### ISSUE THREAD

**Issue by ilkkau** [heitzmann/gdspy#125]
Hi,

I'm still using version 1.4.2, but all documentation references seem to be pointing to 1.5.x which is significantly different. What's the easiest way to get access to older documentation?

**Comment by heitzmann** [comment]
Hi @ilkkau, the documentation can be built from the source code with [Sphinx](https://www.sphinx-doc.org/) simply by:
```sh
python setup.py build build_sphinx
```
Otherwise, apart from tutorials, the API docs are all in the code itself, so it is easy to check any class or function with
```python
help(gdspy)
help(gdspy.Polygon)
help(my_cell.add)
```
and so on within a python terminal.
