### ISSUE TITLE
Use gdspy in Klayout Macro developement

### ISSUE THREAD

**Issue by 115017cinDY** [heitzmann/gdspy#139]
Hi Heitzmann:
I am trying to use Klayout Macro development for running my python code. When I import gdspy, the error is 
cannot import name 'clipper'. 
How can I fix it?

**Comment by heitzmann** [comment]
@115017cinDY Clipper is a C extension, so it must be compiled to work. Are you using Windows? If so, there are pre-compiled releases available for you to install (choose one based on your python version and system). On Linux/MacOS you should use pip to compile and install.

**Comment by atofini** [comment]
Could you elaborate on how this is done in KLayout though? I can get it working in a virtual env for Conda but not in KLayout
