### ISSUE TITLE
Path with specific unit or shape

### ISSUE THREAD

**Issue by YangXu024** [heitzmann/gdspy#148]
Hi, I want to repeat a unit/cell along a path designed by myself. Now the cellarray could repeat cells along a line, but become limited when along a circle or other complex path. Is there a method to do this? Or I can just repeat every one with the points calculated for each?

**Comment by heitzmann** [comment]
@YangXu024 In this case you have to do it manually using one CellReference for each point along the path, as you said.

**Comment by YangXu024** [comment]
Okay, thanks a lot!
