### ISSUE TITLE
Gds cell load, delete and reference

### ISSUE THREAD

**Issue by YangXu024** [heitzmann/gdspy#155]
Hi,
I want to build a copy of one loaded cell (B) from a exsiting gdspy file. For example, use the reference or cellarray of cell B to make a new array.  It works but when I delete the original cell B, all reference and cellarray disappear too. Is there a way that I can make a copy of exiting cell, but will not disappear when I delete the original cell?

Best,
Yang

**Comment by heitzmann** [comment]
You probably want to use [`Cell.copy`](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.Cell.copy), but without showing the problematic code, it's hard to fully understand the problem.
