### ISSUE TITLE
gdsPy inversion by Boolean operation results in erroraneous geometry 

### ISSUE THREAD

**Issue by SandboChang** [heitzmann/gdspy#160]
As I will need to change the process from etching to evaporation, I am trying to invert my design in gdsPy.
To do that, I have a square representing my chip subtracting the original design in an object.path,
```
# original design, the polygons are contained in the main_testL.path object (using the CPWPath library)
# main_testL.end()

# attempt to invert it
main_inv = gdspy.boolean(cirAl, main_testL.path, 'not', precision=0.0001, max_points=1999)
cell.add(main_inv)
```

However, the resulted gds file looks strange. From the same original file, however I could get the expected output from KLayout.
Here is a comparison between original vs gdsPy vs KLayout.
https://imgur.com/a/yY4KYbk

Would you have any idea what the cause maybe?
My guess is because the main_testL.path is assembled by lots of polygons, and the subtraction by polygon might confuse the program. In KLayout, the inversion was done by layer. Could we do inversion by layer in gdsPy?

**Comment by heitzmann** [comment]
Yes, you can use only the polygons in a specific layer. Just build a list of all the polygons in the layer you want. Alternatively, you can use [`gdspy.Cell.get_polygons(by_layer=True)`](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.Cell.get_polygons) if you'll be using all polygons in a specific cell.

If you can share more information, maybe I can help look into the issue.

**Comment by SandboChang** [comment]
> Yes, you can use only the polygons in a specific layer. Just build a list of all the polygons in the layer you want. Alternatively, you can use [`gdspy.Cell.get_polygons(by_layer=True)`](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.Cell.get_polygons) if you'll be using all polygons in a specific cell.
> 
> If you can share more information, maybe I can help look into the issue.

Thanks for getting back to me. I wish I can provide the code but it is rather long and messy at the moment.
As I have a deadline tomorrow, for now I would use KLayout to perform inversion, then I will return to the issue and study it in more depth.

**Comment by SandboChang** [comment]
Allow me to close it for now, when I have an update I will try to reopen it.
