### ISSUE TITLE
Artifacts in GDSPY boolean operations

### ISSUE THREAD

**Issue by andrewdunsworth** [heitzmann/gdspy#168]
Thank you for this module, it is great.

I have noticed I can get artifacts that occur when doing booleans that involve a `PolygonSet` with many vertices, like this:

![image](https://user-images.githubusercontent.com/8405285/105920101-9c598d80-5feb-11eb-8430-97fb768d5e62.png)

Sometimes, increasing the `max_points` of the boolean operation fixes the artifact, but other times it does not... 

Have you seen similar artifacts?  Do you have a robust solution / work around?

**Comment by andrewdunsworth** [comment]
I found the source of the problem on my end, the way we generated the geometries were leaving <1 nm gaps between the ends of some things and the beginnings of the others.  This flaky rounding error was leading to bad polygon generation...

**Comment by heitzmann** [comment]
@andrewdunsworth Yes, that would definitely be captured in the boolean operation. Glad you found it.
