### ISSUE TITLE
How to install the gdspy package in version 1.4.1

### ISSUE THREAD

**Issue by lhjey** [heitzmann/gdspy#170]
Hi, I try to install gdspy package in version 1.4.1 with command : pip install gdspy==1.4.1, while there is something wrong. So I want to know how to install the version 1.4.1 correctly. 
Thanks!

**Comment by heitzmann** [comment]
Install information is in the README file. You didn't mention what OS you're using and what is the error you are seeing, but if you're on Windows, use a precompiled binary. To use pip and compile it yourself you'll need to install many other dependencies. Another option is to use Anaconda; there's a gdspy package for Anaconda that should work on Windows.

**Comment by lhjey** [comment]
![image](https://user-images.githubusercontent.com/49546927/107116157-54b8e880-68ac-11eb-8948-f810804c576c.png)

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement gdspy==1.4.1
ERROR: No matching distribution found for gdspy==1.4.1

**Comment by heitzmann** [comment]
Strange, for some reason, minor versions from 1.4 are [missing from pypi](https://pypi.org/project/gdspy/#history).

You can download directly from the [1.4.1 release page](https://github.com/heitzmann/gdspy/releases/tag/v1.4.1) or give the url to [pip](https://pip.pypa.io/en/stable/reference/pip_install/):
```sh
python -m pip install --user https://github.com/heitzmann/gdspy/archive/v1.4.1.tar.gz
```

**Comment by lhjey** [comment]
![image](https://user-images.githubusercontent.com/49546927/107116844-0c4ff980-68b1-11eb-8d64-8cf5c6861aab.p
Is it installation successful?The version displayed is still 1.4.

**Comment by lhjey** [comment]
![image](https://user-images.githubusercontent.com/49546927/107116911-77013500-68b1-11eb-9df2-6cfbf47197d0.png)

**Comment by lhjey** [comment]
![image](https://user-images.githubusercontent.com/49546927/107116973-ff7fd580-68b1-11eb-81a4-eec80095c95a.png)

Is it installation successful?The version displayed is still 1.4.

**Comment by heitzmann** [comment]
Yes, this was a problem with the 1.4 release… The version number was stuck at "1.4", but you have the right version.
That's probably the reason why these versions are not available in pypi.

**Comment by lhjey** [comment]
OK, thanks for your help!

**Comment by anujashok194** [comment]
![pp](https://user-images.githubusercontent.com/99434586/153629074-e2390313-93d8-4231-90c0-f80958e61fc2.PNG)
![image](https://user-images.githubusercontent.com/99434586/153629155-9f4d28a4-b5f4-4f2c-8639-d47191624788.png)

Can you please tell me what is the problem?
