### ISSUE TITLE
Is there a way to combine gds files?

### ISSUE THREAD

**Issue by stormyweathers** [heitzmann/gdspy#171]
Hey there,

For organization purposes, it is sometimes easier to generate patterns in separate gds files.  How can I use gdspy to read in cells from multiple files and merge them together into a master layout?

I've tried working with multiple libraries and using lib.extract() to get the desired cells. This gives a warning "Deprecated since version 1.5: extract is deprecated and will be removed in a future version of Gdspy. Gdspy no longer uses a global library.", but there was no suggested alternative.

I ignored the warning, and tried to generate a new master layout using loaded in cells, but it appears to not have the proper cell references.  KLayout doesnt render anything from the loaded-in cells.

How should I proceed?

**Comment by heitzmann** [comment]
Please take a look at #113 and #130.
In KLayout, make sure you are selecting the desired top-level cell on the left side bar.
