### ISSUE TITLE
new release please

### ISSUE THREAD

**Issue by tvt173** [heitzmann/gdspy#174]
@heitzmann , would it be possible to have a new release which includes my fix from a few months back? i know it is very small, but it is required for me in some cases, forcing me to install from source, rather than pip/conda. would be great to have a new release when possible. thanks!

**Comment by heitzmann** [comment]
Sure! I was waiting for more fixes before release, but its been a while now, and I ended up forgetting about it…

**Comment by tvt173** [comment]
thank you! very much appreciated!
