### ISSUE TITLE
Bad resolution gds file in viewer

### ISSUE THREAD

**Issue by MAN6O** [heitzmann/gdspy#176]
Hi, when I open gds files in the gdspy viewer I noticed the bad resolution quality of the window. Is it possiblw to change the resolution to the screen resolution?

**Comment by heitzmann** [comment]
Not really. It just uses the default Tk canvas for drawing at whatever resolution your monitor is configured. LayoutViewer is intended as a quick debug tool, only; it is not meant for full visualizations of large layouts. For that, we advise using something like KLayout.
