### ISSUE TITLE
image to gds

### ISSUE THREAD

**Issue by mo-nu** [heitzmann/gdspy#186]
Hi Heitzmann,

I have the layout images(svg) of the cells. Is there a way to convert it into gds file?

[FreePDK45.zip](https://github.com/heitzmann/gdspy/files/6718216/FreePDK45.zip)

Thanks

**Comment by heitzmann** [comment]
Automatically, no. But looking at a few of those cells, they don't seem too difficult to manually parse. You'd have to write a parser for svg polygons, extract the points and create GDSII cells with them. Labels should be more or less simple to import as well. This project might be a good starting point: https://github.com/meerk40t/svgelements
