### ISSUE TITLE
polygon error

### ISSUE THREAD

**Issue by harrywang2018** [heitzmann/gdspy#187]
one error in polygon class, pls help...
line 431 in polygon.py file, error: "Undefined name ‘total’ (pyflakes E)"

![1](https://user-images.githubusercontent.com/41356460/123574632-c87b7380-d802-11eb-9f3e-327326efd6bc.JPG)

**Comment by heitzmann** [comment]
@harrywang2018 That's a bug in the error message; should be fixed in the latest commit. Thanks!
