### ISSUE TITLE
Copy the cell and reference cell to a new gds library

### ISSUE THREAD

**Issue by ojipadeson** [heitzmann/gdspy#188]
I want to copy a cell and its reference cells to a new library, so I use cell.copy, codes are as follow:

(cell is from this library)
`
gds_file = gdspy.GdsLibrary(infile='frame.gds')
`
`
top_cell = target_gds.top_level()[0]
`

(cell will be copying to this library)
`
lib = gdspy.GdsLibrary()
`
`
new_top_cell = frame_lib.new_cell('top')
`

(I use deep_copy=True to copy)
`
frame = lib.new_cell('frame')
`
`
frame.add(top_cell.copy(top_cell.name, deep_copy=True))
`
But reference cell is enclosed in brackets after copying, and all of them are not shown.
Is there anything wrong with the copy() function?

Thanks for any feedback

**Comment by heitzmann** [comment]
Hi @ojipadeson, there's no need to create a copy if you only want to save a new library:
```python
gds_file = gdspy.GdsLibrary(infile='frame.gds')
top_cell = target_gds.top_level()[0]
lib = gdspy.GdsLibrary()
lib.add(top_cell, include_dependencies=True)
lib.write_gds("new_file.gds")
```
You'd only need a copy if you want to modify a cell but keep a copy of the original.
Note that [`add`](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.GdsLibrary.add) includes all dependencies by default.

Also, this line is incorrect: `frame.add(top_cell.copy(top_cell.name, deep_copy=True))`. It adds a cell to another cell; that doesn't work. If you want a reference, you have to create a [reference](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.CellReference): `frame.add(gdspy.CellReference(top_cell))`
