### ISSUE TITLE
Is there any way i can attach label with a polygon?

### ISSUE THREAD

**Issue by mansigupta1998** [heitzmann/gdspy#191]

**Comment by heitzmann** [comment]
No, polygons and labels are independent. You can attach properties to both, though.

**Comment by mansigupta1998** [comment]
Thanks for your fast response.
Can you explain what all properties.
My problem statement is that,  after importing gds if I move any polygon, label attach to that polygon should move as well but not vice versa.
Also this attachment would help in various other things.

**Comment by heitzmann** [comment]
There is no element attachment in the GDSII format. Labels are placed independently of polygons. If you move a label, only the label moves. The same goes for polygons. If you need a structure that moves together, place both the polygon and the label in a cell and move the cell reference around.

Properties are dictionaries associated to GDSII elements. You can access them through the [`properties`](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.PolygonSet) variable.

**Comment by mansigupta1998** [comment]
Ok thank you
