### ISSUE TITLE
Encounter a problem when using get_polygons with (layer, datatype)

### ISSUE THREAD

**Issue by billycsu** [heitzmann/gdspy#196]
Dear Sir,

I just encountered a problem when trying to obtain all polygons with specific layer and datatype.
I tried to use get_polygons(by_spec=(x,y)) but the line 690 of library.py response an error message:

FlexPath doesn't have datatype property.

Then I tried to modify line #690 of library.py: "path.datatype" to "path.datatype**s**", then it solved the problem.

**Comment by heitzmann** [comment]
Thanks for the report!
