### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by anujashok194** [heitzmann/gdspy#206]
![image](https://user-images.githubusercontent.com/99434586/153631203-3b4d0807-bcfe-4971-b2fe-a98fe2284d15.png)
![image](https://user-images.githubusercontent.com/99434586/153631260-d0d112bb-61a5-4eca-ad30-fe218cf7246b.png)

Can you please help me with this?

**Comment by heitzmann** [comment]
Did you install gdspy on the same virtual environment you're trying to use it from? On the Command Prompt where you installed gdspy, does the following command work: `python -c "import gdspy"`?

**Comment by anujashok194** [comment]
No its not working

**Comment by heitzmann** [comment]
How did you install it the first time? On Windows, gdspy need a properly configures development environment for compilation of C extensions. If your environment is not configured correctly, it will appear to have been installed but it won't be. If that's the case, uninstall it with pip (as you did the first time) or manually remove all files from site-package and use one of the provided wheels (_*.whl_) in the [releases page](https://github.com/heitzmann/gdspy/releases/tag/v1.6.11).

**Comment by anujashok194** [comment]
![image](https://user-images.githubusercontent.com/99434586/153637197-5918196b-8e0b-451c-9e7a-9bae6b6be67f.png)

Thank you. It work.
