### ISSUE TITLE
'Cell' object has no attribute 'elements'

### ISSUE THREAD

**Issue by CongjiangCST** [heitzmann/gdspy#223]
When I ran my code:
```
filepath = './test.gds'
gdsii = gdspy.GdsLibrary()
gdsii.read_gds(filepath)
cell = gdsii.top_level()[0]
print(len(cell.elements))
```
I got an error:
`AttributeError: 'Cell' object has no attribute 'elements'`
My environment is python3.7.4 and gdspy 1.6.12.
Can anyone give me some advice to solve it?
Thanks.

**Comment by heitzmann** [comment]
@CongjiangCST `Cell` objects don't have `elements`, they have `name`, `polygons`, `paths`, `labels`, and `references`.
Please take a look at the [documentation](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.Cell).
