### ISSUE TITLE
[Documentation] What does "intersect, but not cross" mean?

### ISSUE THREAD

**Issue by shamefulCake1** [heitzmann/gdspy#241]
This phrasing is encountered in `gettingstarted.rst`.

As far as I remember English, "intersect" and "cross" mean exactly the same thing.

Could the wording be changed to explain what this actually means?

**Comment by heitzmann** [comment]
Please read the wikipedia link and it should be pretty clear. Coincident segments have an intersection without properly crossing each other. Adjacent segments in a polygon have an intersection and do not cross each other either.
