### ISSUE TITLE
Rectangle fillet precision being ignored

### ISSUE THREAD

**Issue by pjdeeb** [heitzmann/gdspy#41]
Value entered for precision doesn't seem to affect the result in any way. Expected result would be all points being on a grid of size precision but that doesn't seem to be the case.

**Comment by heitzmann** [comment]
@pjdeeb The problem there is that the documentation is not clear — `precision` is used only for fracturing. If no fracture is required (number of vertices in the resulting polygon less than `max_points`), `precision` is not used.
Fixed in 1f9f80a954b60c045326dd10b42c53ce45b8e1b2.
