### ISSUE TITLE
Error in transformation of label coordinates

### ISSUE THREAD

**Issue by johnmfini** [heitzmann/gdspy#44]
In the definition of CellReference, polygons are (correctly) transformed according to 
```
polygons[kk][ii] = polygons[kk][ii] * ct \
                                + polygons[kk][ii][:, ::-1] * st
```
(e.g. x<- cos(theta) x - sin(theta) y, but labels are transformed according to:
```
lbl.position = lbl.position * ct + lbl.position * st
```
(e.g. x<- cos(theta) x - sin(theta) x), which is not consistent or unitary.  The label formula should be corrected to follow the same formula as the polygons.  
```
lbl.position = lbl.position * ct + lbl.position[::-1] * st
```
This correction fixed the disagreement I was seeing with a layout viewed in klayout.

**Comment by heitzmann** [comment]
Thanks @johnmfini! I've included the fix in https://github.com/heitzmann/gdspy/commit/5fd94974ba8a4171fdef3d2a22bea7d16727898e
