### ISSUE TITLE
polygon in clockwise or counterclockwise

### ISSUE THREAD

**Issue by enuinc** [heitzmann/gdspy#45]
Hi

maybe not totally related to gdspy, but I just wonder if there is a common convention regarding the polygon vertices orientation in GDS file. The file I am opening has counter-clockwise but I read somewhere that GDS format does not dictate one way or the other. Is this true? How to express holes in a polygon then?

Thanks
enuinc

**Comment by heitzmann** [comment]
Hi @enuinc, that's right, there is no convention for polygon orientation in GDSII. It's also not possible to draw polygons with holes. However, it is okay to have polygons self-intersect along edges, so holes can be introduced by connecting them to the outer edge.
For example, take a look at [gdspy.Round](http://gdspy.readthedocs.io/en/latest/geometry.html#gdspy.Round) with `inner_radius` ≠ 0 in the [tutorial](http://gdspy.readthedocs.io/en/latest/tutorial.html#tutorial).
