### ISSUE TITLE
Layer patterning does not work on Mac

### ISSUE THREAD

**Issue by rubenvanstaden** [heitzmann/gdspy#50]
![screen shot 2018-05-20 at 2 05 43 pm](https://user-images.githubusercontent.com/6705245/40278741-1eafb48c-5c37-11e8-9971-50f000110174.png)

As shown in the attached figure, the layer patterning doesn't work on macOS Sierra. I have tried to solve this issue myself, but was unable to do so. This becomes extreme tedious for large circuits.

**Comment by heitzmann** [comment]
This is a known issue with Tkinter in Mac OS (https://stackoverflow.com/questions/35994986/tkinter-stipple-option-misbehaving-in-os-x).
In any case, the built-in LayoutViewer is meant as a small preview, for large layouts I strongly suggest using a dedicated external viewer, such as KLayout.
