### ISSUE TITLE
RuntimeWarning for not supported items

### ISSUE THREAD

**Issue by Alex1y** [heitzmann/gdspy#66]
Path ends with custom size are not supported
Record type BGNEXTN (30) is not supported
Record type ENDTEXTN (31) is not supported

**Comment by heitzmann** [comment]
As the warning says, those fields are not currently supported.
Unfortunately I don't have the time right now to implement support form them, but any contributions are welcome!

**Comment by heitzmann** [comment]
Fixed in 81a3998
