### ISSUE TITLE
Individual filleting of each corner in fillet function broken

### ISSUE THREAD

**Issue by PSpring** [heitzmann/gdspy#70]
Trying to fillet each corner of a shape individually by giving the fillet function a list of fillet values matching the number of corners of the polygon is broken. I think this happened in commit:

https://github.com/heitzmann/gdspy/commit/fb3b1b32aeac1680e0d7821a4196f3af11e18190#diff-2812b20adf756d7db06ec54a53840a66

Doing so now will result in errors of the kind: 

`
Traceback (most recent call last):
  File "...\gdspy\__init__.py", line 448, in fillet
    l = radius * tt[ii]
TypeError: can't multiply sequence by non-int of type 'numpy.float64'
`

This functionality seems to have been lost when the Polygon class was cleaned up and made to inherit from the PolygonSet class. Beforehand, the fillet function in the Polygon class had a few lines that PolygonSet does not:

        ct = numpy.cos(theta * 0.5)
        tt = numpy.tan(theta * 0.5)
        if not isinstance(radius, list):
            radius = [radius] * len(self.points)
        if not len(self.points) == len(radius):
            raise ValueError("[GDSPY] Fillet radius list length does not "
                             "match the number of points in the polygon.")
         new_points = []

(lines 377 to 381 in the above commit)

Currently, in PolygonSet the same section looks like:

https://github.com/heitzmann/gdspy/blob/34474d10ab0f247291c06c329819b4943124d9db/gdspy/__init__.py#L429-L432

So when Polygon inherited fillet from PolygonSet, the individual corner filleting functionality to was lost.

Hopefully, simply reinserting these lines into the PolygonSet class should be enough to restore this really useful functionality.

**Comment by heitzmann** [comment]
Thanks @PSpring! I believe 958e31e35214cc456e8996284e94c77fef14ca01 fixes this bug.

**Comment by PSpring** [comment]
No problem! Thanks for the super quick fix!
