### ISSUE TITLE
GDS Manipulation Question

### ISSUE THREAD

**Issue by jlaw** [heitzmann/gdspy#71]
Is it possible to read in a GDS, cut out a region of interest (ROI), and save the ROI to a new file, while keeping hierarchy with gdspy? I am currently using the slice function, but the resulting file is flat.

**Comment by heitzmann** [comment]
@jlaw I don't believe it's possible... For example, if a cell includes `CellArray` of other cells and only a few of those instances are cut by the ROI boundary, what would happen to the hierarchy? The resulting geometry cannot be viewed as a single `CellArray` any longer. A similar issue happens with `CellReference`.

**Comment by jlaw** [comment]
@heitzmann In that scenario I think a copy of the `CellArray` should be made; shrink the original `CellArray` to fit the ROI; new array should be flattened; anything except the shapes/polygons touching the ROI border should be deleted; the remaining shapes should be sliced; sliced shapes inside ROI should be added back to cell.

Are the methods in place to perform these operations? I can imagine I have to get the origin of a `CellArray` or `CellReference`, along with the bounding box and perform the math in Python to determine whether the cell is within the ROI. Is there a method to flatten `CellReference`s one level of hierarchy only?

**Comment by heitzmann** [comment]
@jlaw The best you can use is `CellReference.get_polygons` and `CellArray.get_polygons` but you'll have to create a new hierarchy. Imagine a situation where the main cell references c1 and c2, and c1 also references c2. You might end up with many different versions of c2 depending on how each reference intersects the ROI boundary, specially if they are array references.

In any case, if you find an acceptable solution and wish to include in Gdspy, that function could be useful to other users.
