### ISSUE TITLE
When dealing with circles the output points are reduced by library

### ISSUE THREAD

**Issue by aayushraina** [heitzmann/gdspy#74]
When dealing with circles, I am converting it to set of 32 points. However gdspy is reducing the number of points in the circle. Is it #clip function which is doing it or #fracture

        poly3 = gdspy.fast_boolean(my_list1, my_list2, operation, max_points=5000, layer=776)

Input

![image](https://user-images.githubusercontent.com/23273834/48245707-3a181080-e412-11e8-8d18-be32f142660a.png)

Output

![image](https://user-images.githubusercontent.com/23273834/48245722-50be6780-e412-11e8-8b59-f717b636232e.png)

[InputandOutput.zip](https://github.com/heitzmann/gdspy/files/2564760/InputandOutput.zip)

**Comment by heitzmann** [comment]
@aayushraina Your geometry doesn't look fractured, so I believe it's the `clip` (inside [`fast_boolean`](https://gdspy.readthedocs.io/en/latest/geometry.html#gdspy.fast_boolean)) doing the simplification. It is probably related to the `precision` parameter. Have you tried changing it from the default 1e-3 to something like 1e-6?

The library that performs the clipping operation works only with integer coordinates, so the geometry is scaled by dividing by this factor, then all coordinates are converted to integer, the operation is performed, and finally the resulting coordinates are multiplied by the same factor. Depending on your drawing scale (default: *s = 1 µm*) and the precision you set (default: *1e-3 * s = 1 nm*), some of the coordinates might lie on top of each other and end up merged.

**Comment by aayushraina** [comment]
Thanks . I will check and update. For now I am closing the issue.
