### ISSUE TITLE
Mac OS X Mojave upgrade breaks ability to compile GDSPY

### ISSUE THREAD

**Issue by amccaugh** [heitzmann/gdspy#76]
# The problem

After upgrading to OS X Mojave (10.14), I am no longer able to compile gdspy, and the pip wheel install fails.  This is due to OS X deprecating the use of the "stdlibc++" headers in favor of the "libc++" headers I believe.  To reproduce:

Download the gdspy master branch and try to compile it on a computer with OS X Mojave:
`python setup.py install`

returns the following error:

```
...
building 'gdspy.clipper' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.6m -c gdspy/clipper.cpp -o build/temp.macosx-10.7-x86_64-3.6/gdspy/clipper.o -std=c++11
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the
      command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]
In file included from gdspy/clipper.cpp:49:
gdspy/clipper.hpp:56:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1
```

# The solution

This can be fixed by adding a couple compile/link flags for OS X, inspiration taken from this [stackexchange answer](https://stackoverflow.com/questions/52460913/compiling-cython-with-xcode10)

In setup.py, add the new flags somewhere near the top:

```
import platform 

if platform.system() == "Darwin":
    compile_extra_args = ['-std=c++11', "-mmacosx-version-min=10.9"]
    link_extra_args = ["-stdlib=libc++", "-mmacosx-version-min=10.9"]
```

and then add the linker arguments to the `Extension` calls:

```
    ext_modules=[
        Extension('gdspy.boolext', ['gdspy/boolext.c'],
                         extra_compile_args=compile_extra_args,
                         extra_link_args=link_extra_args),
        Extension('gdspy.clipper', ['gdspy/clipper.cpp'],
                         extra_compile_args=compile_extra_args,
                         extra_link_args=link_extra_args)
    ],
```

# Caveats

I'm not sure if this plays nicely with older versions of OS X (pre-Mojave).  It may be necessary to add some kind of platform.release() comparison to make sure that it doesn't mess up e.g. Sierra installs, but I imagine this can be tested in Travis relatively easily.

**Comment by amccaugh** [comment]
I created a PR to fix this issue, might be worth double-checking on another system but I've checked it on one Mojave system and one High Sierra system and it works well

**Comment by amccaugh** [comment]
@heitzmann Any chance of applying a hotfix for this?  (Until the next version is out, 1.3.1 can't be installed on Mojave without hand-modifying the setup.py file).  I believe all that's needed is to cherry-pick the following commits into the master branch:

`git cherry-pick 7350af7 ffef69f dfb70a5 0550bbb` 

then bump the version number (e.g. `1.3.2`)

Thoughts?

**Comment by heitzmann** [comment]
Sure, I though `next` would be released sooner, but I got caught up on other stuff.
