### ISSUE TITLE
translating paths does not translate endpoints

### ISSUE THREAD

**Issue by amatherbishop** [heitzmann/gdspy#83]
Since the translate function is inherited directly from PolygonSet, the endpoints path.x and path.y are not updated.

**Comment by heitzmann** [comment]
Thanks, fixed in f00e632.

**Comment by heitzmann** [comment]
My bad, I was in a rush and didn't take into account the other transformations.
I believe now it should work in all cases that make sense (scaling by different amounts in x and y being the exception).
