### ISSUE TITLE
Doubts regarding the usage of built-ins in gdspy

### ISSUE THREAD

**Issue by ShruthiLS** [heitzmann/gdspy#87]
1. Is there any possibility of converting pointlist into path.
2. Can we use the .turn built in to polygon list or is it mandatory to use only with the path function.

**Comment by heitzmann** [comment]
Hello @ShruthiLS,

1. I'm not sure I understand exactly what you need, but take a look into [FlexPath](https://gdspy.readthedocs.io/en/stable/gettingstarted.html#flexible-paths)
1. The `Path.turn` method can only be used to create polygonal curves in `Path` objects ([see here](https://gdspy.readthedocs.io/en/stable/gettingstarted.html#polygonal-only-paths)). I don't understand how it could be used with a polygon list. What are you expecting it to do?
