### ISSUE TITLE
PLEX is not supported

### ISSUE THREAD

**Issue by thesourcerer8** [heitzmann/gdspy#90]
I am getting this warning when trying to read gds files generated by librecell (https://codeberg.org/tok/librecell)
UserWarning: [GDSPY] Record type PLEX (2F) is not supported.
gdspy.current_library.read_gds(a)
You can get an example file here:
https://www2.futureware.at/ftp/db/0e54c51c7b78491a32bf593a6aeeccbba89c795b/upload.gds

**Comment by heitzmann** [comment]
@thesourcerer8 Do you use the PLEX information for anything? I have never seen that field being used in practice, that's why it is not supported. Otherwise you can simply ignore the warning.
