### ISSUE TITLE
Issue while extending polygons

### ISSUE THREAD

**Issue by lsshruthi** [heitzmann/gdspy#99]
layer1 = 5
layer2 = 8
shapes = cv.get_polygons(by_spec=True, depth=0)
met1_drn = (shapes[layer1,0])
for dummy_shape in met1_drn:
	extension = 10
         ptlist = dummy_shape + numpy.array([[0,-extension],[0,+extension],[0,+extension],
[0, -extension]])    #this is working fine with extension in y direction.
	ptlist = dummy_shape + numpy.array([[extension,0],[extension,0],[-extension,0],[-extension,0]])  #its not giving the proper extension in the x direction.
	new_line  =	cv.add(gdspy.Polygon(ptlist,layer2))

In the above code,extension in y direction is working as expected but not in x direction. Any changes to make in code.

**Comment by heitzmann** [comment]
It seems to me it should work, unless the polygons are not what you expect them to be. Have you checked that the vertices are in the order you expect. You might have to use `numpy.array([[-extension,0],[-extension,0],[extension,0],[extension,0]])`. It's hard to tell for sure without knowing the polygons...
